/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as ExpenseReportIndexRouteImport } from './routes/expenseReport/index'
import { Route as CashflowIndexRouteImport } from './routes/cashflow/index'
import { Route as BankIndexRouteImport } from './routes/bank/index'
import { Route as AlertIndexRouteImport } from './routes/alert/index'
import { Route as DashboardIndexRouteImport } from './routes/Dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/Auth/index'
import { Route as Ai_CoachIndexRouteImport } from './routes/Ai_Coach/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseReportIndexRoute = ExpenseReportIndexRouteImport.update({
  id: '/expenseReport/',
  path: '/expenseReport/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowIndexRoute = CashflowIndexRouteImport.update({
  id: '/cashflow/',
  path: '/cashflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIndexRoute = BankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIndexRoute = AlertIndexRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/Dashboard/',
  path: '/Dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/Auth/',
  path: '/Auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ai_CoachIndexRoute = Ai_CoachIndexRouteImport.update({
  id: '/Ai_Coach/',
  path: '/Ai_Coach/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Ai_Coach': typeof Ai_CoachIndexRoute
  '/Auth': typeof AuthIndexRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/alert': typeof AlertIndexRoute
  '/bank': typeof BankIndexRoute
  '/cashflow': typeof CashflowIndexRoute
  '/expenseReport': typeof ExpenseReportIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Ai_Coach': typeof Ai_CoachIndexRoute
  '/Auth': typeof AuthIndexRoute
  '/Dashboard': typeof DashboardIndexRoute
  '/alert': typeof AlertIndexRoute
  '/bank': typeof BankIndexRoute
  '/cashflow': typeof CashflowIndexRoute
  '/expenseReport': typeof ExpenseReportIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Ai_Coach/': typeof Ai_CoachIndexRoute
  '/Auth/': typeof AuthIndexRoute
  '/Dashboard/': typeof DashboardIndexRoute
  '/alert/': typeof AlertIndexRoute
  '/bank/': typeof BankIndexRoute
  '/cashflow/': typeof CashflowIndexRoute
  '/expenseReport/': typeof ExpenseReportIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Ai_Coach'
    | '/Auth'
    | '/Dashboard'
    | '/alert'
    | '/bank'
    | '/cashflow'
    | '/expenseReport'
    | '/insights'
    | '/logout'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Ai_Coach'
    | '/Auth'
    | '/Dashboard'
    | '/alert'
    | '/bank'
    | '/cashflow'
    | '/expenseReport'
    | '/insights'
    | '/logout'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/Ai_Coach/'
    | '/Auth/'
    | '/Dashboard/'
    | '/alert/'
    | '/bank/'
    | '/cashflow/'
    | '/expenseReport/'
    | '/insights/'
    | '/logout/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Ai_CoachIndexRoute: typeof Ai_CoachIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AlertIndexRoute: typeof AlertIndexRoute
  BankIndexRoute: typeof BankIndexRoute
  CashflowIndexRoute: typeof CashflowIndexRoute
  ExpenseReportIndexRoute: typeof ExpenseReportIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenseReport/': {
      id: '/expenseReport/'
      path: '/expenseReport'
      fullPath: '/expenseReport'
      preLoaderRoute: typeof ExpenseReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow/': {
      id: '/cashflow/'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/': {
      id: '/bank/'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard/': {
      id: '/Dashboard/'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/': {
      id: '/Auth/'
      path: '/Auth'
      fullPath: '/Auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Ai_Coach/': {
      id: '/Ai_Coach/'
      path: '/Ai_Coach'
      fullPath: '/Ai_Coach'
      preLoaderRoute: typeof Ai_CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Ai_CoachIndexRoute: Ai_CoachIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AlertIndexRoute: AlertIndexRoute,
  BankIndexRoute: BankIndexRoute,
  CashflowIndexRoute: CashflowIndexRoute,
  ExpenseReportIndexRoute: ExpenseReportIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
